version: '3.8'

services:
  server:
    build: ./server
    container_name: servapp_c
    ports:
      - "6247:6247"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: evanclin_c
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    stdin_open: true
    tty: true