version: '3.8'

services:
  server:
    build: ./server
    container_name: serverapp
    ports:
      - "6247:5000"
    volumes:
      - ./client:/app
      - ./app/node_modules
    depends_on:
      - client

  client:
    build: ./client
    container_name: evan-on-dock
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
